#!/bin/bash

if [ -z $1 ]; then
	echo "No className given."
	exit 1
fi

className=F$(echo ${1}| sed 's/\(.\)/\U\1/')
fileName=${className}
productInterfaceName=${2}
location=${3+"${3}/"}


cat << _EOF_ >> ${location}${fileName}.java
public class ${className} {
	public enum E${productInterfaceName}Type {
		DEFAULT
	}

	private static ${className} a_oInstance = null;
	private Vector<${productInterfaceName}> a_lProducts = null;
	
	private ${className}(){
		a_lProducts = new Vector<${productInterfaceName}>();
	}

	private ${productInterfaceName} Fx_BuiltDefaultProduct() {
		return null;
	}

	private void Fx_RemoveProduct(int iProduct) {
		
	}

	public static ${className} GetInstance() {
		if(a_oInstance != null) { return a_oInstance; }
		a_oInstance = new ${className}();
		return a_oInstance;
	}
	
	public ${productInterfaceName} BuiltProduct(E${productInterfaceName}Type eType) {
		${productInterfaceName} oProduct;

		switch (eType) {
			case DEFAULT: oProduct = Fx_BuiltDefaultProduct(); break;
			default: break;
		}

		a_lProducts.add(oProduct);
		return oProduct;
	}

	public ${productInterfaceName} GetProduct(int iProduct) {
		if(iProduct < 0 || iProduct >= a_lProducts.size()) { return NULL; }
	
		return a_lProducts.get(iProduct);
	}

	public List<${productInterfaceName}> GetProducts(Iterable<int> liProducts) {
		Vector<${productInterfaceName}> loProducts = new Vector<${productInterfaceName}>();
		for(int iProduct : liProducts) {
			${productInterfaceName} oProduct = GetProduct(iProduct);
			if(oProduct == null) { continue; }
			loProducts.push_back(oProduct);
		}

		return loProducts;
	}

	public void DestroyProduct(int iProduct) {
		${productInterfaceName} oProduct = GetProduct(iProduct);
		if(oProduct == null) { return; }
		a_lProducts.set(iProduct, null);
	}

	public void DestroyProducts(Iterable<int> liProducts) {
		for(int iProduct : liProducts) { DestroyProduct(iProduct); }
	}
}
_EOF_
