#!/bin/bash

if [ -z $1 ]; then
	echo "No className given."
	exit 1
fi

className=M$(echo ${1}| sed 's/\(.\)/\U\1/')
fileName=${className}
location=${2+"${2}/"}


cat << _EOF_ >> ${location}${fileName}.java
public class ${className}
{
	private static ${className} a_oInstance = null;
	private boolean a_bIsSetUp = false;
	private boolean a_bIsShutDown = true;

	private ${className}() {
		a_bIsShutDown = false;
		a_bIsSetUp = false;
	} 

	public static ${className} GetInstance() {
		if(a_oInstance != null) { return a_oInstance; }
		a_oInstance = new ${className}();
		return a_oInstance;
	}

	public void SetUp() {
		if(a_bIsSetUp) {
			return; 
		}
		a_bIsShutDown = false;

		// TODO ${className} SetUp

		a_bIsSetUp = true;
	}

	public void ShutDown() {
		if(a_bIsShutDown) {
			return; 
		}
		a_bIsSetUp = false;

		// TODO ${className} ShutDown

		a_bIsShutDown = true;
	}
}
_EOF_
